### ISSUE TITLE
UI Enhancement: "Continue" button as a top button in the starting menu

### ISSUE THREAD

**Issue by Factorionaut** [Velociraptor115-DSPModding/DSPMods#21]
**Mod**
UIEnhancements

**Proposed Feature**
Position swap between the "New Game" and "Continue" buttons in the game's starting menu

**Expected Benefit**
Quick and smooth transition to resuming the previous gaming session without the hassle of looking up the "Continue" button, utilizing the brain's natural inclination towards easy solutions.

**Comment by Velociraptor115** [comment]
Let me see if I can make that happen

**Comment by Velociraptor115** [comment]
@Factorionaut Have added this feature in 0.0.5 version of the mod. Like all other enhancements, you will have to enable it explicitly for the first time.
Let me know if you find it useful

**Comment by Factorionaut** [comment]
It's working perfectly, as expected. Thank you.
🤝
