### ISSUE TITLE
[BetterWarning] liquid mining insufficient

### ISSUE THREAD

**Issue by cyan** [Velociraptor115-DSPModding/DSPMods#23]
the mod is working great but it would be nice to have a way to filter out liquid extractor like the water pump and oil extractor as they always end up having an insufficient rate.

**Comment by Velociraptor115** [comment]
That is weird, can you attach a screenshot of what you mean?
As far as I know, pumps and oil extractors do not have the vein depletion warning 🤔

**Comment by cyan** [comment]
not the depleted one but the "near depletion" one
![Capture d'écran 2024-01-16 195155](https://github.com/Velociraptor115-DSPModding/DSPMods/assets/90098/36b0e865-9ace-42e6-aae2-8f29b5292356)

**Comment by cyan** [comment]
i had this trouble in 2022 when i last played and just started playing again and it s there again with a fresh install of the r2modman

**Comment by Velociraptor115** [comment]
Will look into it today

**Comment by Velociraptor115** [comment]
Let me know if the issue is not fixed
